const router = require('express').Router();
const adminController = require('../controllers/adminController');
const asyncHandler = require('../utils/asyncHandler');
router.get('/users', asyncHandler(adminController.listUsers));
router.get('/users/:id', asyncHandler(adminController.getUserDetails));
router.put('/users/:id/status', asyncHandler(adminController.setUserStatus));
router.delete('/users/:id', asyncHandler(adminController.deleteUser));
router.get('/sources', asyncHandler(adminController.listAdminSources));
router.post('/sources', asyncHandler(adminController.createSource));
router.put('/sources/:id', asyncHandler(adminController.updateSource));
router.delete('/sources/:id', asyncHandler(adminController.deleteSource));
router.get('/articles', asyncHandler(adminController.listAdminArticles));
router.get('/articles/:id', asyncHandler(adminController.getAdminArticle));
router.delete('/articles/:id', asyncHandler(adminController.deleteAdminAnalysis));
router.get('/flagged', asyncHandler(adminController.listFlagged));
router.put('/flagged/:id', asyncHandler(adminController.updateFlagged));
router.get('/analytics', asyncHandler(adminController.analytics));
router.get('/system', asyncHandler(adminController.systemConfig));
router.get('/notifications', asyncHandler(adminController.listAdminNotifications));
router.put('/notifications/read-all', asyncHandler(adminController.markAllNotificationsRead));
router.put('/notifications/:id/read', asyncHandler(adminController.markNotificationRead));
module.exports = router;
