const router = require('express').Router();
const analysisController = require('../controllers/analysisController');
const { analysisLimiter } = require('../middleware/rateLimit');
const asyncHandler = require('../utils/asyncHandler');
router.post('/jobs', analysisLimiter, asyncHandler(analysisController.startJob));
router.get('/jobs/:jobId', asyncHandler(analysisController.getJob));
router.post('/url', analysisLimiter, asyncHandler(analysisController.analyzeFromUrl));
router.post('/content', analysisLimiter, asyncHandler(analysisController.analyzeFromContent));
router.get('/history', asyncHandler(analysisController.getHistory));
router.get('/summary', asyncHandler(analysisController.getSummary));
router.get('/:id/report', asyncHandler(analysisController.downloadReport));
router.post('/:id/reanalyze', analysisLimiter, asyncHandler(analysisController.reanalyze));
router.post('/:id/share', asyncHandler(analysisController.enableShare));
router.delete('/:id/share', asyncHandler(analysisController.disableShare));
router.post('/:id/feedback', asyncHandler(analysisController.submitFeedback));
router.get('/:id', asyncHandler(analysisController.getById));
router.post('/:id/save', asyncHandler(analysisController.toggleSave));
router.delete('/:id/save', asyncHandler(analysisController.toggleSave));
router.delete('/:id', asyncHandler(analysisController.deleteById));
module.exports = router;
