export const TERMS_SECTIONS = [
  { title: '1. Acceptance of Terms', body: ['By creating an account or using TruthLens AI ("the Service"), you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the Service.', 'We may update these terms from time to time. Continued use of the Service after changes are posted constitutes acceptance of the revised terms.'] },
  { title: '2. Description of Service', body: ['TruthLens AI is an AI-assisted news credibility analyzer. It accepts news article URLs and produces a credibility assessment covering source reliability, evidence quality, claim consistency, publication transparency, writing quality and sensationalism.', 'The Service is provided for informational and educational purposes. It is not a newsroom, not a fact-checking certification body and not a substitute for professional journalistic or legal judgment.'] },
  { title: '3. Accounts and Security', body: ['To use analysis features you must register with an accurate name and email address. You are responsible for keeping your credentials confidential and for all activity under your account.', 'We use bcrypt password hashing, JWT sessions, one-time email codes for sign-in and role-based access control. You must not attempt to access another user\'s data, bypass security controls, or access admin functions without authorization.', 'We may suspend accounts that violate these terms or that are used for abusive, unlawful or fraudulent activity.'] },
  { title: '4. Acceptable Use', body: ['You agree not to use the Service to: analyze content you do not have the right to use; attempt to disrupt, overload or probe the infrastructure; extract or scrape data in bulk; resell or redistribute analysis outputs as your own service; or use the Service for any unlawful purpose.', 'You may analyze articles for personal research, education and media-literacy purposes.'] },
  { title: '5. Credibility Assessments Are Not Absolute Truth', body: ['TruthLens AI produces probabilistic, evidence-based credibility assessments. Verdict levels such as "Highly Credible", "Potentially Misleading" or "Highly Suspicious" describe how well an article\'s sourcing, evidence, transparency and writing patterns hold up to structured scrutiny at the time of analysis.', 'These assessments are NOT declarations that any article, claim or source is definitively true or false. Always verify important information using reliable primary and independent sources.'] },
  { title: '6. Intellectual Property', body: ['TruthLens AI software, branding, design and content are owned by the TruthLens AI project. Analyzed articles remain the property of their respective publishers and rights holders; the Service only quotes short passages for analysis purposes.', 'Your account data belongs to you. You may download and export your analysis history and PDF reports.'] },
  { title: '7. Privacy', body: ['Your privacy is governed by our Privacy Policy, which forms part of these terms. We do not sell your personal data.'] },
  { title: '8. Limitation of Liability', body: ['The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, TruthLens AI and its operators are not liable for decisions made in reliance on analysis outputs, including but not limited to publishing, investment, legal or safety decisions.', 'Where external information retrieval or AI services are unavailable, the Service will clearly indicate reduced functionality (for example, claims marked "Needs Verification") rather than fabricating results.'] },
  { title: '9. Termination', body: ['You may delete your account and data at any time. We may terminate or restrict access for violations of these terms. Provisions that by their nature should survive termination (liability limits, IP clauses, dispute resolution) will survive.'] },
  { title: '10. Governing Law', body: ['These terms are governed by the laws of the Republic of India. Disputes shall be subject to the exclusive jurisdiction of the courts of India.'] },
  { title: '11. Contact', body: ['Questions about these terms can be directed to the support address published on the Service.'] }
];
export const PRIVACY_SECTIONS = [
  { title: '1. Introduction', body: ['This Privacy Policy explains what information TruthLens AI collects, why we collect it, how it is used and the choices available to you. By using the Service you agree to the practices described here.'] },
  { title: '2. Information We Collect', body: ['Account data: your full name, email address, optional profile picture, role, account status and settings such as two-factor preferences.', 'Authentication data: hashed passwords (bcrypt), Google OAuth identifiers when you sign in with Google, and one-time code records used to protect sign-ins and password resets.', 'Content you submit: the article URLs and pasted article content you analyze, together with the resulting analysis reports.', 'Technical data: server logs with IP addresses and timestamps, used for security and abuse prevention.'] },
  { title: '3. How We Use Information', body: ['We use your data to: operate your account and sessions; run article extraction and AI credibility analysis on content you submit; send one-time verification codes and security alerts; show your analysis history, statistics, saved reports and notifications; moderate flagged content; and improve the Service.', 'AI analysis content may be sent to third-party AI providers (for example Google Gemini) solely to produce the analysis you requested. We do not use your submitted articles for training external models beyond the provider\'s standard API data handling.'] },
  { title: '4. Cookies and Local Storage', body: ['We use local storage in your browser to remember your session token and your theme preference. We do not use third-party advertising cookies.'] },
  { title: '5. Data Sharing', body: ['We do not sell personal data. Data is shared only with: service providers that operate the infrastructure and AI analysis (under data-processing obligations); authorities when required by law; and other parties only with your consent.', 'Article-level analysis results may be visible to you and, for moderation, to administrators of the Service.'] },
  { title: '6. Data Retention', body: ['Account data is kept while your account is active. Analyses and reports remain available to you until you delete them. One-time codes are deleted after use or expiry (minutes). Deleted accounts trigger deletion of associated analysis, claim, notification and report records.', 'Aggregated, anonymized statistics may be retained for service improvement.'] },
  { title: '7. Your Rights', body: ['You may access, correct or delete your personal data at any time from your profile and settings pages, or by contacting support. You may also disable two-factor codes or email preferences, download your PDF reports, or delete individual analyses.', 'You may request account deletion, which removes your personal data as described in section 6.'] },
  { title: '8. Security', body: ['We protect data with bcrypt password hashing, JWT session tokens, expiry-limited single-use codes, role-based authorization enforced server-side, CORS and rate limiting, and by never exposing API keys in frontend code.', 'No method of transmission or storage is completely secure. You share responsibility by keeping your password confidential and using strong, unique credentials.'] },
  { title: '9. Children', body: ['The Service is not directed at children under 13, and we do not knowingly collect their personal data. If you believe a child has provided data, contact us so we can remove it.'] },
  { title: '10. Changes to This Policy', body: ['We may update this Privacy Policy. Material changes will be announced in the Service. Your continued use after changes constitutes acceptance.'] },
  { title: '11. Contact', body: ['For privacy questions, contact the support address published on the Service.'] }
];
export function sectionsToPlainText(sections) {
  return sections.map((s) => `${s.title}\n${s.body.join(' ')}`).join('\n\n');
}
